### PR TITLE
fix multiple js comments in a html comment

### LINKED ISSUE #321: CSS comments in HTML comments
CSS comments present in the HTML typically the file documentation seem to break modulizer.

see: https://github.com/PolymerElements/app-layout/blob/master/app-grid/app-grid-style.html#L84
result: https://github.com/PolymerElements/app-layout/blob/__auto_generated_3.0_preview/app-grid/app-grid-style.js#L163

### PR DESCRIPTION
**Pull request by e111077**
fixes #321

### CODE REVIEW

File: src/document-util.ts [hunk 1]
```diff
@@ -428,7 +428,7 @@ export function attachCommentsToFirstStatement(
     statements[0]!;
 
   const recastComments: RecastComment[] = comments.map((comment) => {
-    const escapedComment = comment.replace('*/', '*\\/');
+    const escapedComment = comment.replace(new RegExp('\\*/', 'g'), '*\\/');
```
Comment (stramel) [inline src/document-util.ts]: Not sure if this would be preferred to `new Regex`, `/\*\//g`?

**Comment by FredKSchott** [comment]
From: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace  
> "Only the first occurrence will be replaced."

Doh! Good catch.
